reearth/reearth-cms

.github/workflows/server.yml, server/Dockerfile, server/go.mod, server/go.sum
- update go ver
- update dependencies
- update docker file
- update ci
=> chore(server): update dependencies

web/package.json, web/src/App.tsx, web/src/components/pages/Authentication/RootPage/index.tsx, web/yarn.lock
I've used [React Router](https://reactrouter.com/) because `Reach Router` will be [migrated to it](https://reactrouter.com/docs/en/v6/upgrading/reach)
=> feat(web): add routing

server/gqlgen.yml, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_asset.go, server/internal/adapter/gql/resolver_mutation_asset.go, server/internal/adapter/gql/resolver_query.go, server/schemas/asset.graphql
In this PR I added the following:
1- asset.graphql schema
2- generated initial gqlgen files
=> feat(server): add asset to GraphQL schema

web/package.json, web/src/components/atoms/Button/index.tsx, web/src/components/atoms/CustomTag/index.tsx, web/src/components/atoms/DownloadButton/index.tsx, web/src/components/atoms/Icon/index.tsx, web/src/components/atoms/ProTable/index.tsx, web/src/components/atoms/Radio/index.tsx, web/src/components/atoms/TilesetPreview/index.tsx, web/src/components/atoms/Tree/index.tsx, web/src/components/atoms/Upload/index.tsx, web/vite.config.ts, web/yarn.lock
In this PR I did the following:
1- Added AntDesign's ProTable, Radio, Tree and Upload components as atom components.
2- Added DownloadButton as atom component to download any file by providing a file name and a url.
3- Added TilesetPreview as atom component to preview tileset files.
4- Added CustomTag as atom component.
5- updated `vite.config.ts` file to make Cesium and ProTable work.
=> feat(web): asset ui atom components

server/internal/app/app.go, web/package.json, web/vite.config.ts, web/yarn.lock
I changed vite port to always be `3000` to make sure login works (port 3000 is added to Auth0)
=> feat(web): update dependencies

web/codegen.yml, web/src/gql/fragmentMatcher.json, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/field.ts, web/src/gql/queries/model.ts
Added queries for both schema (create) and model (create/get)
Added additional queries to the set of queries
Any syntax mistakes/errors
=> feat(web): schema graphQL

web/package.json, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/field.ts, web/src/gql/queries/model.ts, web/yarn.lock
Added additional GrqphQL queries
Added both `update/delete` for model and field schemas and `check model key availability` query
=> feat(web): add schema queries

.github/workflows/server_deploy_test.yml, .github/workflows/web.yml
=> ci: set up deploy workflow for test env

web/package.json, web/vite.config.ts, web/yarn.lock
Because it's more convenient to open browser when web server runs
=> chore(web): open browser window when dev server runs

web/src/components/molecules/ProjectList/ProjectCard.tsx, web/src/components/molecules/ProjectList/ProjectList.tsx, web/src/components/molecules/Workspace/WorkspaceHeader.tsx, web/src/components/molecules/Workspace/index.tsx
=> chore(web): update project card UI/UX

web/src/components/atoms/InnerContents/basic.tsx, web/src/components/molecules/CMSWrapper/index.tsx, web/src/components/molecules/Common/Header/index.tsx, web/src/components/molecules/ProjectOverview/ModelCard.tsx, web/src/components/molecules/ProjectOverview/index.tsx, web/src/components/molecules/Public/index.tsx, web/src/components/molecules/Schema/index.tsx, web/src/components/organisms/Project/ModelsMenu/hooks.ts, web/src/components/organisms/Project/ModelsMenu/index.tsx
=> feat(web): affix header and sidebar to top and left, respectively

web/src/components/organisms/Asset/Asset/index.tsx
In this PR I added a spinner to asset page
=> feat(web): add spinner to asset page

.github/workflows/deploy_test.yml, .github/workflows/worker.yml, .github/workflows/worker_build.yml, worker/Dockerfile
=> ci(worker): set up worker deploy

go.work.sum, server/pkg/schema/field_url.go
=> fix(server): URL field default value should accept empty string

web/src/components/molecules/Content/List/index.tsx, web/src/components/molecules/Schema/index.tsx
I added the model key as a subtitle to:
- Schema header (changed custom header to the pageHeader to be more consistent)
- Content header
As requested in the Figma
=> feat(web): add model key

web/src/components/atoms/ProTable/index.tsx
Remove additional `;` added by mistake
=> fix(web): remove unecessary character

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
=> fix(web): clear select default value if item option not available

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_field.go, server/internal/usecase/interactor/schema.go, server/internal/usecase/interfaces/schema.go, server/pkg/schema/field.go, server/pkg/schema/field_test.go, server/schemas/field.graphql
=> fix(server): save unique, multiValue, and required on update

server/pkg/integration/integration_type.go, server/pkg/integration/integration_type_test.go
=> fix(server): integration type not stored

web/src/components/molecules/MyIntegrations/Webhook/WebhookForm/index.tsx, web/src/components/molecules/MyIntegrations/Webhook/WebhookList/WebhookCard/index.tsx
- FE: updating the webhook is switching it off
- FE: fix spacing of the webhook edit buttons (on the card)
=> fix(web): keep active status when updating webhook

web/src/components/molecules/MyIntegrations/CreationModal/index.tsx
Make integration type public by default (when creating)
=> fix(web): make integrations public by default

web/src/components/molecules/Schema/fieldTypes.ts
Update fields cards on the schema page with meaningful descriptions
=> feat(web): update schema fields description

server/internal/infrastructure/mongo/model.go
model key should be unique on the project scope only
=> fix(server): remove unique index for the model key

server/internal/usecase/interactor/item.go
parsing fails for empty int values
skip the value if value == ""
=> fix(server): skip empty int values

web/src/i18n/translations/ja.yml
Add missing Japanese translation strings.
=> feat(web): restore Japanese translations

web/src/components/organisms/Project/Schema/hooks.ts
=> fix(web): keep selected model while switching between schema and content pages

server/go.mod, server/go.sum, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/convert_user.go, server/internal/adapter/gql/gqlmodel/convert_user_test.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/app/auth_client.go, server/internal/usecase/operator.go, server/pkg/user/role.go, server/pkg/user/role_test.go, server/schemas/workspace.graphql, server/tools.go
Added the maintainer role for the user pkg and to the gql, add the maintainable workspace and maintainable projects to the operator
=> feat(server): add maintainer role

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/schemas/workspace.graphql
=> fix(server): capitalize maintainer role in GraphQL schema

web/src/components/molecules/Asset/AssetListTable/index.tsx, web/src/utils/file.ts
In this PR I implemented only displaying status for zip files.
=> fix(web): only display status for zip files

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx, web/src/components/molecules/Schema/types.ts, web/src/components/organisms/Project/Schema/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/field.ts, web/src/utils/values.ts
=> fix(web): reflect backend schema changes

web/src/components/molecules/MyIntegrations/CreationModal/index.tsx
Integrations should be private by default (When created)
=> feat(web): make integration private by default

web/src/components/molecules/Common/CommentsPanel/Editor.tsx
Change comment word count to be 1000
=> feat(web): comment word count to be 1000

server/internal/usecase/interactor/model.go, server/internal/usecase/interactor/schema.go, server/internal/usecase/interactor/usecase.go, server/internal/usecase/operator.go
I've updated the permissions checks to be like [this](https://www.notion.so/eukarya/Roles-3c07daec56ca49bca225bd2e2bb417d9)
=> fix(server): role checks

server/gqlgen.yml, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/convert_request.go, server/internal/adapter/gql/gqlmodel/convert_request_test.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_request.go, server/internal/usecase/interactor/request.go, server/pkg/request/list.go, server/pkg/request/list_test.go, server/schemas/request.graphql
- fix the reviewers resolver 
- change closeAll func -> UpdateStatus
- add `createdBy` resolver
- only waiting requests can be approved
=> fix(server): only waiting requests can be approved

server/internal/usecase/interactor/request.go, server/internal/usecase/interactor/request_test.go
add testcase
- fix `Approve` function
- add test case to ensure that it works
=> fix(server): item has no public ref after approval

web/src/components/molecules/Common/Header/index.tsx
Add a tooltip when hovering over the workspace name on the header menu items
=> feat(web): add tooltip to header menu items

web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldDefaultInputs/SelectField/index.tsx
=> feat(web): allow to delete default value after added

server/internal/infrastructure/gcp/webhook.go, server/internal/usecase/interactor/item.go, server/pkg/integrationapi/convert.go, server/pkg/integrationapi/event.go, server/pkg/integrationapi/schema.go, server/pkg/integrationapi/types.gen.go, server/pkg/item/item.go, server/schemas/integration.yml, worker/pkg/webhook/webhook.go
=> feat(server): add operator field to webhook payload

web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
Refetch requests query after creating/updating the request
=> feat(web): refetch requests after create/update

server/internal/usecase/interactor/request.go, server/internal/usecase/interactor/request_test.go
I changed the request approval to run as a transaction, after approving success I triggered the related webhook for all items in the request
=> feat(server): item publish webhook

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx
In this PR I fixed the mvt name regex
=> fix(web): mvt name regex

web/src/components/molecules/Asset/AssetList/index.tsx, web/src/components/molecules/Common/Form/AssetItem/index.tsx
In this PR I allowed all file formats to be uploadded as asset
=> fix(web): support all asset file formats

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx, web/src/components/molecules/Asset/Viewers/MvtViewer/index.tsx
In this PR I set Japan as the default location for mvt files
=> feat(web): set japan as the default location for mvt

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx
In this PR I fixed the bug when mvt resets viewer location on every click.
=> fix(web): mvt resets viewer location on every click

web/src/components/atoms/ResiumViewer/index.tsx, web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx, web/src/components/molecules/Asset/Viewers/Geo3dViewer/index.tsx, web/src/components/molecules/Asset/Viewers/GeoViewer/index.tsx, web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx, web/src/components/molecules/Asset/Viewers/MvtViewer/index.tsx
In this PR I fixed the bug that causes the viewer to re-render on every click and I did some refactoring
=> fix(web): viewer re-rendering + refactor

web/src/components/molecules/Asset/InfoBox/index.tsx
In this PR I made the color of the title based on the theme of infobox
=> style(web): infobox title color

worker/pkg/decompressor/decompressor.go
Reverts reearth/reearth-cms#575
=> Revert "fix(worker): add numWorkers and queueSize & refactor assetFilePath"

web/src/components/molecules/Asset/InfoBox/index.tsx
I did a basic styling for InfoBox based on the figma designs
=> style(web): basic styling for infobox

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx
In this PR I added layer name input to mvt viewer
=> feat(web): add layer name input to mvt viewer

web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx, web/src/components/molecules/Asset/Viewers/Geo3dViewer/index.tsx
In this PR I added the functionality to auto load the tileset.json file for 3dtiles assets
=> feat(web): auto load tileset.json for geo 3d viewer

web/src/components/organisms/Project/Content/hooks.ts
=> fix(web): extend limit of request list(workaround)

web/src/components/atoms/InnerContents/basic.tsx, web/src/components/atoms/Markdown/index.tsx, web/src/components/molecules/Common/CommentsPanel/index.tsx, web/src/components/molecules/ProjectList/ProjectCard.tsx, web/src/components/molecules/ProjectOverview/ModelCard.tsx, web/src/components/organisms/Project/Request/RequestDetails/hooks.ts, web/src/index.css
Fixes:
- Model with long description should replace the overflown part with an ellipsis
- When adding a comment to a certain request the page needs refreshing before the comment is shown
- Markdown default value is overflowing
- Should add padding bottom to account page
- Asset table’s width should be fixed
- Comment sidebar should be expandable/collapsable when clicking on the upper comment icon
- The column’s width in asset’s table should be fixed
=> fix(web): ui improvements

server/internal/usecase/repo/container.go
=> fix(server): add AssetUpload

server/internal/infrastructure/gcp/file.go, web/src/components/organisms/Asset/AssetList/hooks.ts
=> fix(web,server): set content-type to signed URL from GCS

server/Dockerfile, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_asset.go, server/internal/infrastructure/fs/file.go, server/internal/infrastructure/gcp/file.go, server/internal/usecase/gateway/file.go, server/internal/usecase/interactor/asset.go, server/internal/usecase/interfaces/asset.go, server/schemas/asset.graphql, web/src/components/organisms/Asset/AssetList/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/assets.ts
=> fix(web,server): improved asset content-type setting for gcs upload via signed url

worker/internal/infrastructure/fs/file.go, worker/internal/infrastructure/fs/file_test.go, worker/internal/infrastructure/gcp/gcs.go, worker/internal/usecase/gateway/file.go, worker/internal/usecase/interactor/decompress.go, worker/pkg/decompressor/decompressor.go, worker/pkg/decompressor/decompressor_test.go
=> feat(worker): resumable decompressor

server/internal/app/m2m.go, worker/internal/usecase/interactor/decompress.go
=> chore(server,worker): improve error message

worker/internal/infrastructure/gcp/gcs.go
=> feat(worker): add retry policy

server/internal/app/m2m.go
=> chore(server): fix format string

server/internal/infrastructure/gcp/file.go
=> fix(server): change to fallback on failure to issue signed url

server/pkg/asset/file.go, server/pkg/asset/file_test.go
=> perf(server): improve FoldFiles performance

server/pkg/thread/comment_test.go
=> chore(server): remove flaky test

.github/workflows/decompressor_build.yml, server/internal/app/repo.go
=> chore(worker,server): tiny fix for decompressor

.github/workflows/ci_server.yml, .github/workflows/ci_worker.yml
=> chore(ci): fixed actions are triggered when build_*.yml is changed

worker/decompressor.Dockerfile
=> feat(worker): use gcs-unzip v0.1.2

worker/decompressor.Dockerfile
=> feat(worker): use gcs-unzip v0.1.3

worker/decompressor.Dockerfile
=> feat(decompressor): use gcs-unzip v0.1.4

server/internal/infrastructure/mongo/asset_file.go
=> fix(server): fixed an error if asset files are empty

server/internal/usecase/interactor/asset.go, server/internal/usecase/interactor/asset_test.go
=> fix(server): avoid transaction timeout on asset notify

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
In the options schema type, prevent empty option values
=> feat(web): prevent empty values

web/src/components/molecules/ProjectSettings/index.tsx, web/src/components/organisms/Project/settings/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/project.ts
Add request role form to project settings
=> feat(web): add project request permissions

server/internal/usecase/interactor/item.go, server/internal/usecase/interactor/item_test.go
- Item publishing condition has been fixed to not check if the requestRoles slice is empty
- Update the unit test accordingly
=> fix(server): item publishing condition

server/internal/app/m2m.go, worker/internal/app/handler.go
The GCP changes that were done in these PRs #762 and #729 in the notify, decompress and webhook handlers have been reverted
=> fix: revert GCP changes in the handlers

web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx
- Add copy icon next to images' title
=> feat(web): add copy icon next to images' title

worker/decompressor.Dockerfile
=> fix(worker): use gcs-unzip:v0.1.5 for shiftjis filepath

server/go.sum, server/pkg/item/field_change.go, server/pkg/item/field_change_test.go
Cause: item.CompareFields uses maps internally so the order of the result is not fixed
=> test: fix item.CompareFields test

server/internal/app/config.go, server/internal/app/repo.go
=> feat(server): account database to be configurable

web/src/components/molecules/Content/Details/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/organisms/Project/Content/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/item.ts
- Publish multiple items at once.
=> feat(web): publish multiple items at once

server/go.sum, server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_item.go, server/internal/app/main.go, server/internal/usecase/interactor/item.go, server/internal/usecase/interactor/item_test.go, server/internal/usecase/interfaces/item.go, server/schemas/item.graphql
- Publish multiple items instead of one item
- Rename itemId to itemIds in `UnpublishItemInput`
=> feat(server): publish multiple items at once

server/internal/adapter/gql/resolver_mutation_user.go
check if theme parameter is nil before converting to a pkg model
=> fix(server): update me mutation is throwing nil pointer error 

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/loader_item.go, server/internal/adapter/gql/resolver_query.go, server/internal/usecase/interactor/item.go, server/internal/usecase/interactor/item_test.go, server/internal/usecase/interfaces/item.go, server/schemas/item.graphql
- Add `isItemReferenced` query to check if an item is referenced by any other item
=> feat(server): add isItemReferenced query

server/internal/usecase/interactor/item.go, server/internal/usecase/interactor/item_test.go
- The sItemReferenced query not returning the correct value bug has been fixed
=> fix(server): isItemReferenced query is not returning the correct value

web/src/components/molecules/Schema/FieldModal/FieldCreationModalWithSteps/index.tsx, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Schema/index.tsx
- Disable reference direction on update field modal
- Update the title of the update field modal
=> fix(web): disable reference direction on update field

web/src/components/organisms/Project/Content/ContentList/hooks.ts
- Display item's title for reference in items gird
=> fix(web): display item's title for reference in items gird

web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldCreationModalWithSteps/index.tsx
- Fix `key is not valid` when inputting the same key in update reference field.
=> fix(web): key is not valid in update ref field

web/src/components/molecules/Schema/ModelFieldList.tsx, web/src/components/molecules/Schema/types.ts, web/src/components/organisms/Project/Schema/hooks.ts
- Meta fields order has been fixed
=> fix(web): meta fields order

web/src/components/molecules/Schema/FieldList.tsx, web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx, web/src/components/molecules/Schema/index.tsx, web/src/components/organisms/Project/Schema/hooks.ts, web/src/components/organisms/Project/Schema/index.tsx
=> fix(web): hide isTitle in meta fields

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
- Fix boolean and checkbox default
=> fix(web): boolean and checkbox default value

server/internal/usecase/interactor/schema.go, server/pkg/schema/schema.go, server/pkg/schema/schema_test.go
- The ability to reset `schema.titleField` to `nil` has been added
=> feat(server): add the ability to reset the titleField

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_mutation_field.go, server/schemas/field.graphql
- Delete metadata fields has been fixed
=> fix(server): delete metadata fields

web/src/components/molecules/Content/Form/index.tsx, web/src/components/organisms/Project/Schema/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/field.ts
- Delete metadata fields has been fixed
=> fix(web): delete metadata fields

server/internal/usecase/interactor/item.go, server/internal/usecase/interactor/schema.go
=> feat(server): add self reference support

server/internal/infrastructure/gcp/taskrunner.go, worker/decompressor.Dockerfile
Reverts reearth/reearth-cms#823
=> Revert "feat(server,worker): update gcs-unzip"

server/internal/infrastructure/gcp/taskrunner.go, worker/decompressor.Dockerfile
=> feat(server,worker): update decompressor

web/src/components/organisms/Project/Content/ContentList/hooks.ts
- Reference Item's title has been fixed
=> fix(web): reference item's title

server/e2e/common_test.go, server/internal/app/repo.go, server/internal/infrastructure/mongo/container.go
=> fix(server): fixes so that no one other than reearthx/account is mistakenly used

web/src/i18n/translations/ja.yml
- Japanese translation has been added to group field components
=> chore(web): add group field japanese translation

web/src/components/molecules/Common/Form/GroupItem/index.tsx, web/src/components/molecules/Common/MultiValueField/MultiValueGroup/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldDefaultInputs/GroupField/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldDefaultInputs/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
-  empty group item field's value has been fixed in this PR
=> fix(web): empty group item field's value

web/src/components/molecules/Content/Form/index.tsx
- add performance improvement for content form submission.
=> perf(web): improve content form's submission performance

web/src/components/molecules/Common/Form/GroupItem/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Schema/FieldList.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
- Add date field has been reverted
=> fix(web): revert date field

web/src/components/molecules/Schema/FieldList.tsx
- Reference field has been removed from group
=> fix(web): remove reference field from group

web/src/components/molecules/Schema/FieldModal/FieldValidationInputs/index.tsx
-  Eliminate negative values in min, max and max length
=> fix(web): eliminate negative values in min and max

web/src/components/molecules/Common/Form/GroupItem/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Schema/FieldList.tsx, web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/utils/format.ts
- Date field bugs has been fixed
=> feat(web): implement date field

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
- Group field validation has been disabled
=> feat(web): disable group field validation

web/src/components/atoms/Form/index.tsx, web/src/components/molecules/Common/Form/GroupItem/index.tsx, web/src/components/molecules/Common/MultiValueField/MultiValueGroup/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
- Group default value has been fixed in this PR
=> fix(web): group default value

web/src/components/molecules/Schema/FieldModal/FieldValidationInputs/index.tsx
- This PR fixes the number validation so number fields can be set as minus value
=> fix(web): number field validation

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
- This PR disables validation in boolean fields
=> fix(web): disable boolean field validation

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
- This PR disables boolean fields validation
=> fix(web): disable boolean fields validation

web/src/components/molecules/Common/MultiValueField/MultiValueGroup/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/group.ts
This PR fixes the date field's default value
=> fix(web): date field's default value

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx, web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
- This PR resets multiple value on submit
=> fix(web): multiple value on submit

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
- This PR fixes boolean fields default value
=> fix(web): boolean field's default value

web/src/components/molecules/View/viewsMenu.tsx
Fixed "Save as new view" button position accornding to the design.
=> fix(web):  "Save as new view" button position

web/src/components/organisms/Project/Content/ContentList/hooks.ts
- This PR hides the meta items from content table
=> fix(web): hide meta items from content table

web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
- This PR fixes model is required in searchItem query
=> fix(web): model is required in searchItem query

web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json
- Update gql schema
- Fix search item queries
=> fix(web): update gql schema

web/src/gql/graphql-client-api.tsx, web/src/gql/queries/view.ts
- This PR fixes view's gql query to support the and condition with all its cases
=> fix(web): view's gql query

web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/ViewsMenu/hooks.ts
- This PR fixes the bug where the default view is not loaded correctly
=> fix(web): default view

web/src/components/molecules/View/viewMenuItem.tsx
Fixed view tabs style according to design.
=> fix(web): view tabs style

web/src/components/molecules/Content/Table/DropdownRender.tsx, web/src/components/molecules/Content/Table/types.ts
Fixed tag filter style according to the design.
=> fix(web): tag filter style

web/src/components/molecules/Content/Table/DropdownRender.tsx, web/src/components/molecules/Content/Table/index.tsx, web/src/components/molecules/Content/Table/types.ts, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/ViewsMenu/index.tsx
- Fixed the sort operator initialization issue
- Fixed the redundant codes
- Avoided using assertions as much as possible and added processes of type judgments.
In some cases, it may be better to review the original type definitions and reduce the processes of type judgments.
=> fix(web): redundant codes and type assertion

web/package.json, web/src/components/molecules/Common/CommentsPanel/Comment.tsx, web/yarn.lock
- This PR implements showing the urls as hyperlinks in comments
=> feat(web): show urls as hyperlinks in comments

web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/ContentList/renderFields.tsx
- This PR fixes the bug where single fields are treated as multiple in `fieldRender` method
=> fix(web): check single and multiple fields in field render

web/src/components/molecules/Content/types.ts, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/ContentList/renderFields.tsx
This PR allows you to update metadata except URL from Content Table.
=> feat(web): update metadata except URL from Content Table

web/src/components/molecules/Content/types.ts, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/convertItem.ts, web/src/gql/graphql-client-api.tsx, web/src/gql/graphql.schema.json, web/src/gql/queries/item.ts
This PR fixes the bug which sends the original item's version instead of the metadata item version
=> fix(web): metadata version

web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
This PR fixes the bug where the item and metaitem versions are sent incorrectly
=> fix(web): metaitem version

web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
This PR fixes the bug caused by the complicated logic. I tried to keep it as simple as possible for now.
=> fix(web): initial values of multi assets of multi groups

web/src/components/molecules/Asset/AssetListTable/index.tsx, web/src/components/molecules/Common/ResizableProTable/index.tsx, web/src/components/molecules/Request/Details/SidebarCard.tsx, web/src/components/molecules/Request/Details/index.tsx, web/src/components/molecules/Request/Table/index.tsx, web/src/components/organisms/Workspace/hooks.ts
This PR fixes the quick bugs.
- added new workspace to the workspaces list in the header after creating new one
- fixed the timing of displaying the partial 404 on Request page
- fixed the styling of the table after selecting any rows
=> fix(web): workspaces list, partial 404, and styling

web/src/components/molecules/Schema/ModelFieldList.tsx
This PR fixes the bug and always shows entry information and publish status in meta field list
=> fix(web): always show entry information and publish status

web/src/components/molecules/Settings/FormModal.tsx, web/src/components/molecules/Settings/index.tsx, web/src/components/molecules/Workspace/types.ts, web/src/components/molecules/WorkspaceSettings/GeneralForm.tsx, web/src/components/organisms/Settings/General/index.tsx
This PR fixed the following:
- Unify the workspace and project settings
- Save workspace settings when clicking on the save button instead of auto saving
=> fix(web): unify settings

web/src/components/molecules/Common/MultiValueField/index.tsx, web/src/components/molecules/Content/Details/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/molecules/Content/types.ts, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Content/utils.ts, web/src/components/organisms/Project/Request/RequestList/hooks.ts
This PR fixes some bugs caused when creating or updating item. I refactored some codes to have codes understandable ant fix the bugs.
- Fixed the bug that the metadata was different on the table and on the item edit page, before creating metadata.
- Refactored the code about creating and updating item.
- Fixed the bug that we can't add a new value to multiple meta text and url.
- Had the date metadata cleared by pressing clear button.
=> fix(web): metadata default value and item creating and updating

web/src/components/molecules/Asset/Viewers/GltfViewer/Imagery.tsx
This PR enable to preview gltf/glb file
=> fix(web): enable to preview gltf/glb file

server/internal/infrastructure/gcp/taskrunner.go, worker/decompressor.Dockerfile
=> fix(worker,server): update decompressor

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx, web/src/components/molecules/Asset/Viewers/MvtViewer/imagery.test.ts
This PR adds a maximum level of zoom to the MVT imagery provider
=> fix(web): mvt maximum zoom level

web/src/utils/file.test.ts, web/src/utils/format.test.ts, web/src/utils/id.test.ts, web/src/utils/path.test.ts, web/src/utils/regex.test.ts, web/src/utils/sort.test.ts, web/src/utils/stringUtils.test.ts
This PR adds unit tests for utils functions
=> test(web): add unit tests for utils functions

web/src/components/molecules/Content/Details/index.tsx, web/src/components/molecules/Content/Form/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts, web/src/components/organisms/Project/Content/ContentDetails/index.tsx, web/src/components/organisms/Project/Content/ContentList/hooks.ts
=> refactor(web): referenced items

web/src/components/molecules/Asset/Viewers/MvtViewer/Imagery.tsx, web/src/components/organisms/Project/Asset/AssetList/hooks.ts, web/src/components/organisms/Project/Asset/AssetList/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/index.tsx, web/src/components/organisms/Project/Content/ContentList/hooks.ts, web/src/components/organisms/Project/Request/RequestDetails/index.tsx, web/src/components/organisms/Project/Schema/index.tsx, web/src/gql/graphql-client-api.tsx, web/src/gql/queries/assets.ts
This PR mainly unifies `GetAssets` and `GetAssetsItems`, and fixes the way to show multi-assets on the content table.
=> fix(web): reduce the queries to get assets

web/src/components/molecules/Schema/FieldModal/FieldCreationModalWithSteps/index.tsx
This PR fixes the reference fields bugs
- Disable model change on update reference field
- Disable unique validation in two-way reference fields
=> fix(web): reference field bugs

server/internal/infrastructure/gcp/file.go
=> fix(server): Fixed to use parameter uuid instead of generated uuid

server/internal/infrastructure/mongo/item_search.go
I projected the asset doc to have only the file name to reduce the result doc size
=> fix(server): item search mongo pipeline

web/src/components/atoms/DownloadButton/index.tsx, web/src/components/molecules/Asset/Asset/AssetBody/UnzipFileList.tsx, web/src/components/molecules/Asset/types.ts
This PR improves the performance of the asset file list
=> perf(web): asset file list

web/src/components/atoms/ProTable/index.tsx, web/src/components/molecules/Asset/AssetListTable/index.tsx, web/src/components/molecules/Common/LinkAssetModal/LinkAssetModal.tsx, web/src/components/molecules/Common/ResizableProTable/index.tsx, web/src/components/molecules/Content/LinkItemModal/index.tsx, web/src/components/molecules/Content/LinkItemRequestModal/LinkItemRequestModal.tsx, web/src/components/molecules/Content/List/index.tsx, web/src/components/molecules/Content/Table/index.tsx, web/src/components/molecules/Content/Table/types.ts, web/src/components/molecules/Integration/IntegrationTable/index.tsx, web/src/components/molecules/Request/Table/index.tsx
This PR also refactors the codes related to the table.
=> feat(web): implement resizable columns on Integration table

web/src/components/molecules/Common/WorkspaceCreationModal/index.tsx
This PR adds a spinner when creating a new workspace
=> feat(web): add a spinner when creating a new workspace

web/src/components/molecules/Member/MemberTable/index.tsx
This PR  implement workspace owners' ability to remove other owners
=> feat(web): implement workspace owners' ability to remove other owners

web/src/components/atoms/Notification/index.tsx
This PR reduces the notification duration to 2 seconds
=> feat(web): reduce the notificatoin duration

web/src/components/molecules/Asset/Viewers/SvgViewer/index.tsx
This PR fixes the bug that the svg source code is not sowing due to cors errors
=> fix(web): view svg source code

server/internal/infrastructure/gcp/file.go
This PR updates the content type handling for files uploaded to GCS via URL, ensuring that SVG images are correctly identified and processed.
=> chore(server): update content type handling for uploaded SVG images via URL

server/internal/infrastructure/mongo/mongodoc/view.go, server/internal/infrastructure/mongo/mongodoc/view_test.go
This PR adds order to view document
=> fix(server): add order to view document

web/package.json, web/vite.config.ts, web/yarn.lock
This PR adds version suffix to cesiumBaseUrl in vite.config.ts
=> feat(web): add version suffix to cesiumBaseUrl

server/e2e/integration_asset_project_test.go, server/e2e/integration_item_test.go, server/internal/adapter/integration/asset.go, server/internal/adapter/integration/convert.go, server/internal/adapter/integration/server.gen.go, server/internal/infrastructure/memory/item.go, server/internal/infrastructure/mongo/item_search.go, server/pkg/integrationapi/types.gen.go, server/pkg/item/query.go, server/pkg/item/query_test.go, server/schemas/integration.yml
This PR impelents the search functionality for assets in integration api
- Implement search for assets via passing a keyword param in integration api
- Rename `query` to `keyword` in items search in integration api
=> feat(server): implement asset search in integrarion api

web/package.json, web/yarn.lock
This PR upgrades @reearth/core to fix the bug that the point is sometimes not rendered in Geometry field.
=> fix(web): upgrade @reearth/core

web/src/components/organisms/Project/Asset/AssetList/hooks.ts
This PR fixes the problem that the asset upload button is activated before all uploading process is completed.
=> fix(web): asset upload button is activated before all uploading process is completed

web/src/components/molecules/Common/ResizableProTable/index.tsx, web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
This PR fixes the bug that publish status is not updated when creating a new request.
Including a small style fixing.
=> fix(web): publish status is not updated when creating a new request

web/src/components/molecules/Common/Form/GeometryItem/index.tsx, web/src/components/molecules/Schema/FieldModal/hooks.ts, web/src/components/molecules/Schema/FieldModal/index.tsx
This PR improves Geometry field.
- Fixing to have camera zoom after searching location.
- Fixing the default selected value of Supported Type on Geometry Editor Field
- Fixing the behavior of validation message of Supported Type
=> fix(web): camera and validation message on geometry field

server/pkg/schema/field_geometry_editor.go, server/pkg/schema/field_geometry_object.go, server/pkg/schema/field_geometry_validation.go
This PR fixes the GeoJSON validation logic to match the specification with other fields.
=> fix(server): geojson validation bug

server/internal/adapter/gql/gqlmodel/convert_schema.go
This PR fixes the bug where if there is a field that is multiple and has multiple default values, if the first value is empty all other values are deleted.
=> fix(server): multiple default value bug

server/schemas/integration.yml
=> doc: fix api doc

web/e2e/project/request.spec.ts, web/src/components/molecules/Request/Details/Request.tsx, web/src/components/molecules/Request/Details/RequestDescription.tsx, web/src/components/molecules/Request/Details/Thread.tsx, web/src/components/molecules/Request/Details/index.tsx, web/src/components/molecules/Request/types.ts, web/src/components/organisms/DataConverters/content.ts, web/src/components/organisms/Project/Request/RequestDetails/hooks.ts, web/src/components/organisms/Project/Request/RequestDetails/index.tsx
This PR adds a link to the item to the request.
=> feat(web): add item link to the request

web/src/components/molecules/Content/RenderField/index.tsx, web/src/index.css
This PR set the max size of popover on content page.
=> fix(web): max size of popover on content page

.github/workflows/ci.yml
=> ci(web): fix deploy-web-pr invalid needs

server/internal/adapter/gql/loader_integration.go
=> feat(server): add 2 minutes delay for integration loader

.github/workflows/deploy_test.yml
=> ci(web): set 100% traffic to latest deploy

web/e2e/general/project.spec.ts, web/e2e/project/accessibility.spec.ts, web/e2e/project/utils/project.ts, web/src/components/molecules/Common/CommentsPanel/Comment.test.tsx
This PR resolves the failing e2e tests in web module
=> fix(web): resolve failing e2e tests

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/resolver_project.go, server/schemas/project.graphql
This PR adds visibility to create project params
=> feat(server): add visibility to create project params

server/internal/infrastructure/gcp/file.go, server/internal/infrastructure/gcp/file_test.go
=> fix(server): update asset upload URL to use custom base URL if configured

.github/workflows/build_web.yml, web/.dockerignore, web/Dockerfile
This PR mounts `/public` directory in Docker build
=> feat(web): mount public directory in docker build

server/internal/app/app.go, server/internal/app/config.go, server/internal/app/m2m_assets.go, server/internal/app/m2m_integration_test.go
=> feat(server): implement M2M API endpoints for asset privacy checks and add integration tests

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/internal/adapter/gql/loader_project.go, server/internal/adapter/gql/resolver_project.go, server/internal/usecase/interactor/project.go, server/internal/usecase/interactor/project_test.go, server/internal/usecase/interfaces/project.go, server/schemas/project.graphql
add CheckProjectLimits on GQL
`query CheckProjectLimits($workspaceId: ID!) {
checkWorkspaceProjectLimits(workspaceId: $workspaceId) {
publicProjectsAllowed
privateProjectsAllowed
}
}`
1. development
2. unit testing
3. local testing
function unit test and local testing
=> feat(server): Check Project Limits GQL

web/src/components/molecules/Common/Header/index.tsx, web/src/components/molecules/Common/WorkspaceMenu/index.tsx, web/src/components/molecules/Workspace/index.tsx, web/src/config/index.ts
This PR updates the disableWorkspaceUi variable type
=> fix(web): correct the type of disableWorkspaceUi env var

server/internal/adapter/gql/generated.go, server/internal/adapter/gql/gqlmodel/convert_user.go, server/internal/adapter/gql/gqlmodel/convert_user_test.go, server/internal/adapter/gql/gqlmodel/models_gen.go, server/schemas/workspace.graphql
=> feat(server): add workspace alias

web/src/components/molecules/Integration/IntegrationTable/index.test.tsx, web/src/components/molecules/Integration/IntegrationTable/index.tsx, web/src/components/molecules/Integration/index.test.tsx, web/src/components/molecules/Integration/index.tsx, web/src/components/organisms/Settings/Integration/hooks.ts, web/src/components/organisms/Settings/Integration/index.tsx
Remove tools of integration table in integration page.
=> fix(web): integrations page table column display issue
