reearth/reearth-cms

web/jest.config.js
web/package.json
web/src/App.tsx
web/src/components/atoms/Avatar/index.tsx
web/src/components/atoms/Breadcrumb/index.tsx
web/src/components/atoms/Button/index.tsx
web/src/components/atoms/Card/index.tsx
web/src/components/atoms/Checkbox/index.tsx
web/src/components/atoms/Comment/index.tsx
web/src/components/atoms/ConfigProvider/index.tsx
web/src/components/atoms/Drawer/index.tsx
web/src/components/atoms/Form/index.tsx
web/src/components/atoms/Icon/index.tsx
web/src/components/atoms/Input/index.tsx
web/src/components/atoms/List/index.tsx
web/src/components/atoms/Modal/index.tsx
web/src/components/atoms/NotFound/index.tsx
web/src/components/atoms/PageHeader/index.tsx
web/src/components/atoms/Skeleton/index.tsx
web/src/components/atoms/Table/index.tsx
web/src/components/atoms/Tabs/index.tsx
web/src/components/atoms/Timeline/index.tsx
web/src/components/atoms/Typography/index.tsx
web/src/components/pages/Authentication/RootPage/index.tsx
web/src/components/pages/NotFound/index.tsx
web/src/gql/provider.tsx
web/src/main.tsx
web/tsconfig.json
web/vite.config.ts
web/yarn.lock

closes #58 
For smoother development by multiple front-end developers soon, preemptively added some components that will most likely be used based on @lavalse current design.
Because of the preemptive nature of this PR, when development is nearing an end on CMS, we should check to make sure all components are being used, and if not, remove them.
In addition:
- Also adds path alias "@reearth-cms". 
- Also removes "import React from "react"" as we are importing the @vitejs/plugin-react rollup plugin that allows us to use modern aspects of React, in particular not needing to write the React import on any components.

[FE] Add basic components from Ant Design

---

server/internal/infrastructure/memory/project.go
server/internal/infrastructure/memory/project_test.go
server/internal/infrastructure/memory/user.go
server/internal/infrastructure/memory/user_test.go
server/internal/infrastructure/memory/workspace.go
server/internal/infrastructure/memory/workspace_test.go
server/pkg/user/user.go
server/pkg/user/user_test.go
server/pkg/util/util.go

- Add `memory.SetUserError`, `memory.SetWorkspaceError` and `memory.SetProjectError` to mock errors from memory repos
- Fix test cases

test(server): mock errors for memory db

---

.vscode/settings.json
go.work
worker/Dockerfile
worker/cmd/reearth-cms-worker/debug.go
worker/cmd/reearth-cms-worker/main.go
worker/cmd/reearth-cms-worker/release.go
worker/docker-compose.yml
worker/go.mod
worker/go.sum
worker/internal/app/app.go
worker/main.go

* Create worker dir
* Introduce [multi-module workspaces](https://go.dev/doc/tutorial/workspaces) so that we can have multiple modules even in the same workspace 
* Add Dockerfile
* Add a simple server which returns "hello world"
* Since Go1.18 supports the multi-module workspaces feature which allows us to have multiple modules under a single workspace though we couldn't do that and were forced to have a hacky way, I've introduced that to take the full advantage of mono-repo. 
* If there is any problem with directory structure, Dockerfile, etc
* The implementation of a simple server since it's a temporary development
* GitHub actions workflow file will be implemented later

feat(server): init worker app with multi-module workspaces

---

web/src/index.css

Roboto 400 is used in the Figma design (as a default font weight), and not included in the project
Added font-weight **400** to the project

feat(web): add new font weight

---

web/src/components/molecules/Schema/ModelCreationModal/index.tsx

Users will be able to create models using a modal including (name/description/key)
Added a new modal component for model creation
Already tested in the acceptance test
Syntax issues

feat(web): add model creation modal

---

web/src/components/molecules/Common/projectMenu/index.tsx
web/src/components/organisms/Project/settings/index.tsx

The schema item in the project menu is an active
Passed the `project id` to the menu and added redirection to the schema page
Tested in the acceptance test

feat(web): add schema redirection item to project menu

---

web/src/components/molecules/Schema/SchemaMenu.tsx
web/src/components/molecules/Schema/types.ts

Added a new molecule component for showing a list of models, and the ability to create new models.
Also added typescript types for both `model` and `field`.
Tested in the acceptance test
Syntax issues

feat(web): add schema menu

---

server/internal/app/app.go
server/internal/app/auth_client.go

In this PR I fixed JWT echo middleware to be sent with rest api requests.
I changed 
`appx.AuthMiddleware(cfg.Config.JWTProviders(), adapter.ContextAuthInfo, false)`
into
`appx.AuthMiddleware(cfg.Config.JWTProviders(), adapter.ContextAuthInfo, true)`
and wrapped the middleware inside `jwtEchoMiddleware` function.

fix(server): jwt echo middleware

---

server/internal/app/app.go
server/internal/app/config.go
server/internal/app/repo.go

* Made cloud tasks optional
* Made M2M config optional
* Because it was inconvenient that developers needed to set it on dev env

fix(server): run server without cloudtasks and m2m config

---

web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldDefaultInputs/URLField/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx

fix(web): model fixes

---

server/pkg/integrationapi/asset.go
server/pkg/integrationapi/comment.go
server/pkg/integrationapi/convert.go
server/pkg/integrationapi/item.go
server/pkg/integrationapi/schema.go
server/pkg/integrationapi/types.gen.go
server/schemas/integration.yml

Changed the format of created at in the integration API from date to date-time.
This allows it to have information such as hours and minutes.
[TIcket](https://www.notion.so/eukarya/BE-add-time-minutes-sec-to-integrationAPI-s-response-a2ab7d81609d4edfa4cfee60f9bda805)

fix(server): change format date to date-time

---

server/pkg/item/item.go

item filter which is used for filtering the items according to the schema fields is missing some newly added fields
keep the original item and only update fields

fix(server): add missing item fields to filter

---

web/src/components/molecules/Common/MultiValueField/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldValidationInputs/index.tsx

In this PR I fixed the following:
- When integer field value is being created or updated with default values existed the frontend sends null.
- When min, max and default values are null the frontend sends 0 instead of null.

fix(web): integer field min, max and default value

---

web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx
web/src/components/molecules/Asset/Asset/AssetBody/index.tsx
web/src/components/molecules/Asset/Asset/AssetBody/previewToolbar.tsx
web/src/components/molecules/Asset/asset.type.ts
web/src/components/organisms/Asset/Asset/hooks.ts
web/src/components/organisms/Asset/Asset/index.tsx
web/src/utils/file.ts

In this PR I did the following:
1- Fixed tileset preview full screen button for `GEO3D` and `MODEL3D` types.
2- Hide full screen button with `Unsupported` viewer type.
3- I refactored the way the asset viewer is displayed.

fix(web): tileset preview + refactor

---

worker/internal/usecase/interactor/decompress.go
worker/internal/usecase/interactor/decompress_test.go
worker/pkg/decompressor/decompressor.go
worker/pkg/decompressor/decompressor_test.go

This commit provides significant improvements to the existing decompression time but it has some caveats including more RAM usage, abandonment to the clean architecture etc. Keeping in mind the PubSub timeout limit it is estimated to have upper limit of 4-5GBs of decompression capacity at the moment hence its a temporary solution.
Decompression rate improvement using concurrency
I've implement a decompression rate improvement solution of BigFiles stored at GCS
I tested it by firing up the worker locally and making a decompression request at the `/api/decompress` endpoint via postman.

perf: decompression rate improvement

---

web/src/components/atoms/Icon/icons.ts
web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx
web/src/components/molecules/Asset/Asset/AssetBody/UnzipFileList.tsx
web/src/components/molecules/Asset/Asset/AssetBody/card.tsx

This PR adds the CopyOutlined icon to asset file names and supports copying the file URL to the clipboard on click. The icon is only visible when an item is selected in the Tree component.
- Added the CopyOutlined icon to the web/src/components/atoms/Icon/icons.ts file.
- Modified the web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx file to include the CopyOutlined icon next to the asset file name.
- Created a CopyIcon styled component for the copy icon's styles.
- Updated the web/src/components/molecules/Asset/Asset/AssetBody/UnzipFileList.tsx file to show the CopyOutlined icon next to the file names in the Tree component.
- Made the CopyOutlined icon visible only when an item is selected in the Tree component.
- Changed the title prop type in the …

feat(web): add copy action

---

server/internal/usecase/interactor/asset.go

when the decompress event was notified, the PreviewType was detected from the decompressed asset and updated,
but if the PreviewType could not be detected, it was updated to an empty string.
fixed to not update when it could not be detected.

fix(server): skip update when PreviewType cannot be detected

---

.github/workflows/deploy_aws.yml
web/amplify.yml

To effectively deploy your project using Amplify, it's crucial to grant Amplify access to the 'web/amplify.yml' file and the 'amplify' folder. These resources are indispensable as they contain the necessary configurations that Amplify requires to correctly deploy your project.
We have also discontinued the use of 'web_ci'. Its utility has been found lacking due to the creation of artifacts with the built project that doesn't sufficiently meet the demands of Amplify. The 'web_ci' process didn't deliver the level of completeness that the Amplify service necessitates for a successful and efficient project deployment.

ci: fix frontend deploying action

---

server/internal/infrastructure/mongo/asset.go

fixed to not add a condition when keyword is an empty string
modified index to be more efficient

perf(server): speed up Asset.FindByProject

---

server/internal/app/auth_client.go

In this PR, the issue of swapped "maintaining projects" and "owning projects" has been fixed.

fix(server): swapped maintaining projects and owning projects

---

web/src/components/molecules/Content/Details/index.tsx
web/src/components/molecules/Content/Form/index.tsx
web/src/components/molecules/Content/RequestCreationModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldCreationModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldUpdateModal/index.tsx
web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
web/src/components/organisms/Project/Content/ContentDetails/index.tsx
web/src/components/organisms/Project/Schema/hooks.ts
web/src/components/organisms/Project/Schema/index.tsx

This PR improves loading state handling.
- Updated the content details component and its related molecules and forms.
- Added a request creation modal and handled loading state.
- Implemented field creation and update modals in the project schema.
- Conducted testing to ensure the updated components and modals are functioning correctly.

feat(web): prevent multi creation clicks

---

web/src/components/molecules/ProjectSettings/RequestOptions.tsx

Use request option has been disabled for reader role in the project settings

fix(web): disable use request for reader role

---

web/src/components/molecules/Asset/Asset/AssetBody/Asset.tsx
web/src/components/molecules/Asset/Asset/AssetBody/UnzipFileList.tsx

- Copy icon has been added to all asset types
- Copy icon has been removed from unzip file list component's title

feat(web): add copy icon to all asset types

---

server/internal/infrastructure/gcp/taskrunner.go
worker/decompressor.Dockerfile

changed to remove the prefix when there is only a directory with the same name as the archive at the top level
changed so that files such as .DS_Store are not uploaded

feat(server,worker): update gcs-unzip

---

server/internal/usecase/interactor/item.go

The "item has been changed before you change it" error appears when trying to update a metadata item. As the version is not important for meta Items I have skipped the version validation for metadata items

fix(server): skip version validation for metadata Items

---

web/src/components/organisms/Project/Content/convertItem.ts

- Display updated by instead of created by in item details page

fix(web): display updateBy's value in item's details

---

server/internal/adapter/gql/generated.go
server/internal/adapter/gql/gqlmodel/models_gen.go
server/internal/adapter/gql/resolver_query.go
server/schemas/_shared.graphql

- `Group` has been added to `NodeType` enum

fix(server): add group to node type

---

web/src/components/molecules/Content/Table/index.tsx

- This PR hides the `createdAt` and `updatedAt` fields from the filter dropdown

fix(web): hide createdAt and updatedAt from filters

---

web/src/components/organisms/Project/Content/ViewsMenu/hooks.ts

Set the default ordering for updates to 'descending.' in the content table

fix(web): content default ordering

---

web/src/components/organisms/Project/Content/ContentList/hooks.ts
web/src/components/organisms/Project/Content/ViewsMenu/hooks.ts
web/vite.config.ts

Set the default ordering in the content table.
Set the default ordering for "updated At" to "descend".

fix(web): set the default ordering in content table

---

web/src/components/molecules/Common/Header/index.tsx
web/src/config.ts

This PR makes it possible to config `editorUrl` in `reearth_config.json`.
If you set `http(s)://ANY_DOMAIN(/)` to the value, the `Go to Editor` button shows up.

fix(web): editor URL setting

---

web/src/components/molecules/Common/ResizableProTable/index.tsx
web/src/components/molecules/Content/Table/index.tsx
web/src/components/molecules/View/types.ts

- This PR fixes the content table's settings menu's fixed property to enable the columns to be fixed to the left or right

fix(web): content table's settings menu's fixed property

---

web/src/components/atoms/InnerContents/basic.tsx
web/src/components/molecules/Common/ProjectMenu/index.tsx
web/src/components/molecules/ProjectOverview/index.tsx
web/src/components/organisms/CMSWrapper/hooks.ts
web/src/components/organisms/Project/Overview/hooks.ts
web/src/components/organisms/Project/Overview/index.tsx

This PR removes the go back home button and adds the home tab to sidebar on Project page.

fix(web): include home tab in sidebar on project page

---

web/src/components/molecules/Common/CommentsPanel/types.ts
web/src/components/molecules/Common/Header/index.tsx
web/src/components/molecules/Common/WorkspaceMenu/index.tsx
web/src/components/molecules/MyIntegrations/Webhook/WebhookForm/index.tsx
web/src/components/organisms/Account/hooks.ts
web/src/components/organisms/Common/CommentsPanel/hooks.ts
web/src/components/organisms/Common/CommentsPanel/index.tsx
web/src/components/organisms/Project/Asset/Asset/index.tsx
web/src/components/organisms/Project/Asset/AssetList/index.tsx
web/src/components/organisms/Project/Content/ContentDetails/index.tsx
web/src/components/organisms/Project/Content/ContentList/index.tsx
web/src/components/organisms/Project/Request/RequestList/index.tsx

This PR fixes the bug shown in the title and a few other quick bugs.
- fixed the bug of the home tab shouldn't always be selected when switching workspace while selecting setting tabs
- fixed the bug of not reflecting comment updates on Asset page
- fixed the refetch queries for the comment mutations
- had updated the display of account name when updating account name
- fixed the language of the notification when updating language setting
- added a required mark on webhook url

fix(web): resolve issues with home tab and asset page comments

---

web/src/gql/fragments/file.ts
web/src/gql/graphql-client-api.tsx
web/src/gql/queries/assets.ts

This pull request addresses the need to enhance the depth of the asset file fragment in our GraphQL queries. The current depth has been increased from 5 to 10.

feat(web): increase asset file fragment depth

---

web/e2e/project/item/metadata/update.spec.ts
web/src/components/molecules/Content/Details/index.tsx
web/src/components/molecules/Content/Form/index.tsx
web/src/components/organisms/Project/Content/ContentDetails/hooks.ts

This PR fixes the behavior of updating metadata for the item that don't have metadata yet.

fix(web): updating metadata added later from edit page

---

server/internal/infrastructure/aws/file.go
server/internal/infrastructure/gcp/file.go
server/internal/infrastructure/mongo/asset_file.go
server/pkg/asset/file.go
server/pkg/asset/file_test.go

This PR fixes the bug where the root file is added to the `asset.files` slice

fix(server): remove the root file from asset files 

---

web/src/components/molecules/Common/ProjectCreationModal/index.tsx

This PR addresses a bug where form fields persist in the create project modal even after the modal is closed

fix(web): clear fields on close in create project modal

---

web/src/components/molecules/Common/ProjectCreationModal/index.tsx

This PR adds initial values to the create project form, improving user experience by pre-filling fields and streamlining the project creation process

fix(web): populate create project form with initial values

---

web/src/components/molecules/Asset/AssetList/index.tsx
web/src/components/molecules/Asset/AssetListTable/index.tsx
web/src/components/molecules/Request/List/index.tsx
web/src/components/molecules/Request/Table/index.tsx
web/src/components/organisms/Project/Asset/Asset/hooks.ts
web/src/components/organisms/Project/Asset/Asset/index.tsx
web/src/components/organisms/Project/Asset/AssetList/hooks.ts
web/src/components/organisms/Project/Asset/AssetList/index.tsx
web/src/components/organisms/Project/Content/ContentList/hooks.ts
web/src/components/organisms/Project/Request/RequestDetails/hooks.ts
web/src/components/organisms/Project/Request/RequestList/hooks.ts
web/src/components/organisms/Project/Request/RequestList/index.tsx

As for Asset and Request, keeping search words is included.

fix(web): keep page number and page size when returning to table from detail

---

web/src/components/molecules/Accessibility/index.tsx

This PR makes the project alias readonly instead of disabled

feat(web): make the project alias readonly instead of disabled

---

web/src/components/molecules/MyIntegrations/Settings/Form.tsx

This PR adds the feature to copy the value of Integration Token.

feat(web): add the button to copy the value of Integration Token

---

web/package.json
web/vite.config.mts
web/yarn.lock

This PR:
- Updates vite version
- Fixes `vite.config` and change the extenstion to .mts

chore(web): update vite and fix vite.config

---

server/internal/usecase/interactor/asset.go
server/pkg/asset/preview_type.go
server/pkg/asset/preview_type_test.go

This PR enhances preview type detection for more file types like czml, geojson, kml, csv, gltf, glb, topojson and mvt

feat(server): enhance preview type detection for more file types

---

web/src/components/molecules/Common/ProjectCreationModal/index.tsx
web/src/components/molecules/Schema/FieldModal/FieldCreationModalWithSteps/index.tsx
web/src/components/molecules/Schema/FieldModal/hooks.ts
web/src/components/molecules/Schema/FieldModal/index.tsx
web/src/components/molecules/Schema/FormModal.tsx
web/src/components/organisms/Project/Schema/hooks.ts
web/src/components/organisms/Project/Schema/index.tsx

This PR removes useless key validating when updating some value other than key.
- Fixing validation failure due to auto filling
- Fixing validation of Reference field

fix(web): remove useless key validating when updating some value other than key

---

.github/workflows/deploy_test.yml

To set the Docker's credential helper.
Ref: [Using a credential helper, Google Cloud](https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling#cred-helper)
Other examples: https://github.com/reearth/reearth-visualizer/blob/e87230d8ff008a68f2fa85aa13f0eead3acbb321/.github/workflows/deploy_server_nightly.yml#L23

fix: add missing repository URL argument for `configure-docker` command

---

.github/workflows/deploy_test.yml

As the title says, I added the missing `actions/checkout` in deploy server workflow.
This is required before `google-github-actions/auth@v2`. 
> Run the actions/checkout@v4 step before this action. Omitting the checkout step or putting it after auth will cause future steps to be unable to authenticate.
>
Ref: [Prerequisites, google-github-actions/auth](https://github.com/google-github-actions/auth)

ci: add missing checkout before deploy server workflow

---

web/src/components/molecules/Content/Form/index.tsx

This PR fixes the bug that changes are not detected for some group fields.
Fixing the logic of detecting changes in a single group field.

fix(web): changes are not detected for some group fields

---

web/e2e/project/item/fields/boolean.spec.ts
web/e2e/project/item/fields/int.spec.ts
web/e2e/project/item/fields/url.spec.ts
web/src/components/organisms/Project/Content/ContentDetails/hooks.ts

This PR fixes the bug group field values sometimes disapper after refreshing page.

fix(web): group field values sometimes disapper after refreshing page

---

web/vite.config.ts

This PR fixes the cesium version in cesiumBaseUrl inside vite.config.ts file
Now the cesium version is coming from `node_modules/cesium/package.json` instead of `package.json`

fix(web): cesium base url version

---

web/src/components/molecules/Asset/UploadModal/UploadModal.tsx

This PR fixes to disable closing modal when uploading asset.

fix(web): disable closing modal when uploading asset

---

web/src/components/molecules/Content/Form/index.tsx

This PR fixes to disable the buttons to change the state of an item based on the item's status.

fix(web): disable the buttons to change the state of an item based on the item's status

---

web/src/components/molecules/WorkspaceSettings/GeneralForm.tsx

This PR fixes the bug that workspace name disappears when refreshing page.

fix(web): workspace name disappears when refreshing page

---

.github/workflows/ci_web.yml
.github/workflows/deploy_test.yml
.github/workflows/web_build.yml
web/.dockerignore
web/Dockerfile
web/docker/40-envsubst-on-reearth-config.sh
web/docker/nginx.conf.template
web/docker/reearth_config.json.template
web/vite.config.ts

I've Dockerized the web application to be portable and deployable to container runtimes (e.g. Cloud Run, Kubernetes). We aim to host the web on Cloud Run.
I've containerised the application and implemented the deployment workflow.
I haven't decommissioned our GCS stuff yet. 
I've implemented it separately from the existing system so that we can deploy, test, and switch over without any impact.
I've built in manually:
```console
$ docker build . -t reearth-cms-web && docker run -e AUTH0_AUDIENCE="https://api.cms.dev.reearth.io" -e AUTH0_CLIENT_ID="xxx" -e AUTH0_DOMAIN="https://reearth-dev.auth0.com" -p 8080:8080 reearth-cms-web
```
Then, I accessed some of the paths and looks okay:
```
$ curl http://localhost:8080/assets/abap-Eabmoog9.js
$ curl http://localhost:8080/reearth_config.json
$ …
```

feat(web): dockerize web application

---

web/Dockerfile
web/docker/40-envsubst-on-reearth-config.sh
web/docker/reearth_config.json.template

I have added some of the missing configuration to `reearth_config.json.template` and the default values to `Dockerfile`.

feat(web): wrap environment variables with '""' for Re:Earth config

---

.github/workflows/cron_ion_token_test.yml
.github/workflows/deploy_test.yml

Add missing permissions to authenticate with Google Cloud with workload federation.
Ran the workflow: [log](https://github.com/reearth/reearth-cms/actions/runs/11427276462/job/31791273143). 
Looks good.

ci: add missing `id-token:write` permission for Google Cloud

---

.github/workflows/build_web.yml
.github/workflows/build_worker.yml

The `${{ github.event.workflow_run.head_branch }}` is empty on workflow run.
The server (API) is working but it is because it's only fixed:
https://github.com/reearth/reearth-cms/blob/9c2d46df481b2ff135db45b22697a776418d5982/.github/workflows/build_server.yml#L29

ci: fix branch retrieval in build workflow for web and worker

---

server/internal/infrastructure/gcp/config.go
server/internal/infrastructure/gcp/taskrunner.go

This adds flexibility to run the jobs on Cloud Build private pools.
- [Create and manage private pools  |  Cloud Build Documentation  |  Google Cloud](https://cloud.google.com/build/docs/private-pools/create-manage-private-pools)
- [Using Cloud Build in a private network  |  Cloud Build Documentation  |  Google Cloud](https://cloud.google.com/build/docs/private-pools/use-in-private-network)
- [Run builds in a private pool  |  Cloud Build Documentation  |  Google Cloud](https://cloud.google.com/build/docs/private-pools/run-builds-in-private-pool)

feat(server): support Cloud Build worker pool

---

server/internal/usecase/interactor/item.go
server/internal/usecase/interactor/item_test.go

Exporting items as GeoJSON does not require a transaction nor operator.

refactor(server): remove operator usage in ItemAsGeoJson

---

web/src/components/organisms/CMSWrapper/hooks.ts

This PR fixes the dashboard account path and removes the workspace alias from the url

fix(web): remove workspace alias from the dashboard account url

---

server/internal/adapter/internalapi/server.go

fix missing /api in public_api_ep
before: http://api.cms.dev.reearth.io/p/test-project-cms-1/test
after: http://api.cms.dev.reearth.io/api/p/test-project-cms-1/test

fix(server): missing /api in public_api_ep

---

go.work.sum
server/cmd/db-migrations/common.go

- Remove `SetNoCursorTimeout(true)` from BatchUpdate function to fix MongoDB Atlas
compatibility issues
- Resolves "noTimeout cursors are disallowed in this atlas tier" error when running
item-migration

fix(server): remove SetNoCursorTimeout for MongoDB Atlas compatibility in db-migrations
